# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gem "fastlane"
gem "cocoapods", ">= 1.16.2"

# Ruby 3.3+ 互換性対応
gem "abbrev"
gem "base64"
gem "bigdecimal"
gem "mutex_m"
gem "nkf"

plugins_path = File.join(File.dirname(__FILE__), 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
