// File generated by firebase-add-app.sh — DO NOT EDIT MANUALLY
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKeXvsSXL3KiGtvCF3RGZZwHhP_6nrwp4',
    appId: '1:535068404458:ios:50092325f0b84d30a7c593',
    messagingSenderId: '535068404458',
    projectId: 'kikiki-apps-overflow5-prod',
    storageBucket: 'kikiki-apps-overflow5-prod.firebasestorage.app',
    iosClientId: '',
    iosBundleId: 'pet.first',
  );
}
